server:
  port: 8085
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arindam-acc/config
          clone-on-start: true
          
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true