server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservices
    username: postgres
    password: root
    
  jpa: 
   hibernate: 
      ddl-auto: update
   show-sql: true
  application:
    name: USER-SERVICE
  config:
    import: configserver:http://localhost:8085
  
  profiles:
    active: 
      - cb,dev
     
    
   
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true

#management:
#  health:
#    circuitbreakers:
#      enabled: true
#      
#  endpoints:
#    web:
#      exposure:
#        include:
#        - health
#        
#  endpoint:
#    health:
#      show-details: always
#      
#resilience4j:
#  circuitbreaker:
#    instances:
#      ratingHotelBreaker :
#       registerHealthIndicator: true
#       eventConsumerBufferSize: 10
#       failureRateThreshold: 50
#       minimumNumberOfCalls: 5
#       automaticTransitionFromOpenToHalfOpenEnabled: true
#       waitDurationInOpenState: 6s
#       permittedNumberOfCallsInHalfOpenState: 3
#       slidingWindowSize: 10
#       slidingWindowType: COUNT_BASED
#       

resilience4j:
  retry:
    instances:
      ratingHotelRetry:
        max-attempts: 3
        wait-duration: 2s
        
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s
       
    

      