server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingservices
    username: postgres
    password: root
    
  jpa: 
   hibernate: 
      ddl-auto: update
   show-sql: true
  config:
    import:
    - configserver:http://localhost:8085
   
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
    
  